steps:
  - name: "hashicorp/terraform:latest"
    entrypoint: sh
    args:
      - "-c"
      - |
        terraform -chdir=infrastructure init
        terraform -chdir=infrastructure apply -auto-approve
  - name: "python:3.11"
    script: |
      #!/usr/bin/env bash
      pip install pipenv
      pipenv install --dev --deploy
      pipenv run lint
      pipenv run typecheck
      pipenv run test
      pipenv requirements > requirements.txt
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - arxiv-updates
      - --region=europe-west3
      - --source=.
      - --entry-point=main
      - --runtime=python311
      - --run-service-account=arxiv-updates-application@clean-fin-392913.iam.gserviceaccount.com
