steps:
  - name: "hashicorp/terraform:latest"
    entrypoint: sh
    args:
      - "-c"
      - |
        terraform -chdir=infrastructure init
        terraform -chdir=infrastructure apply -auto-approve
  - name: "python:3.11"
    entrypoint: bash
    args:
      - "-c"
      - |
        pip install pipenv
        pipenv sync
        pipenv run lint
        pipenv run typecheck
        pipenv requirements > requirements.txt
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - arxiv-updates
      - --region=europe-west3
      - --source=.
      - --runtime=python311
      - --allow-unauthenticated
